### ISSUE TITLE
Heroic Strike "bug"

### ISSUE THREAD

**Issue by Scylla420** [magey/tbc-warrior#12]
Verify that miss penalty from dual wielding is removed while HS/Cleave are queued.

**Comment by TheGroxEmpire** [comment]
### Setup
Target: Target Dummy Level 60
Total hit from character: 8% from gear + 3% from precision talent = 11% hit total
<details>

<summary>Char panel screenshot</summary>

![image](https://user-images.githubusercontent.com/47816228/114294892-c4756a80-9acb-11eb-8b06-0d60dc440225.png)

</details>

### HS queue test
I used an AHK to spam HS button and left Grahandsixty to hit the level 60 target dummy for ~30 mins.
<details>

<summary>Raw log</summary>

[HS_queue_test_1.txt](https://github.com/magey/tbc-warrior/files/6291297/HS_queue_test_1.txt)

</details>

[Warcraft Logs table](https://classic.warcraftlogs.com/reports/m3MfJNZ1BFzxdbgX/#boss=-3&difficulty=0&source=1&type=damage-done)
Total melee swing = 1,250
Total miss = 48
Miss / melee = 3.84%

### Control test
Grahandsixty was doing only auto on level 60 target dummy for ~15 mins on this log.
<details>

<summary>Raw log</summary>

[HS_queue_test_Control_1.txt](https://github.com/magey/tbc-warrior/files/6291301/HS_queue_test_Control_1.txt)

</details>

[Warcraft Logs table](https://classic.warcraftlogs.com/reports/CnXNjQ7qVbdHFxkM/#boss=-3&difficulty=0&type=damage-done&source=1)
Total melee swing = 801
Total miss = 92
Miss / melee = 11.4%

### Conclusion
I think it's pretty clear that HS queue removes DW miss penalty.

**Comment by magey** [comment]
I've measured similar effects, just haven't gotten around to posting them yet; level 58 warrior (290 skill) attacking a level 60 dummy (300 defense) while dual wielding, +3% hit from precision and no +hit from gear. Expected miss chance is `5% + (300-290)*0.1% + 19% - 3%= 22%`.

#### Measured miss chance while only auto attacking:
Melee swings: 6316
Miss chance: **22.02% ±1.02%** (1391)    

#### Measured miss chance while spamming Heroic Strike:
Melee swings: 2553
Miss chance: **9.17% ±1.12%** (234)
