### ISSUE TITLE
Stat Ratings Conversions @ 70

### ISSUE THREAD

**Issue by Cleavis** [magey/tbc-warrior#21]
Check hit rating, crit rating, haste rating, expertise rating, defense rating, dodge rating, parry rating, shield block rating, shield block value, resilience rating @ level 70 for tbc warriors. Also check what happens when you have leftover rating that doesn't add up to 1 skill point, e.g. having leftover defense rating that doesn't add up to 1 defense skill ; does it add fractional amounts of defense skill or does it behave like a breakpoint?

### Offensive Stats
- [x] 15.7692 Hit Rating = 1% hit chance
- [x] 22.0769 Crit Rating = 1% crit chance
- [x] ~~15.7700~~ 15.7692 Haste Rating = 1% haste
- [x] 3.9423 Expertise Rating = 1 expertise; 0.25% reduction of each dodge and parry
- [x] 1 Shield Block Value = +1 damage to Shield Slam (rounds down..? it is a little weird)

### Defensive Stats
- [x] 2.3654 Defense Rating = 1 defense; +0.04% each chance to block, dodge, parry, be missed, reduction to be crit
- [x] 18.9231 Dodge Rating = 1% dodge chance
- [x] ~~22.4000~~ 23.6538 Parry Rating = 1% parry chance
- [x] 7.8846 Shield Block Rating = 1% block chance
- [x] 1 Shield Block Value = +1 damage absorbed on a block (rounds down..? it is a little weird)
- [x] 39.4231 Resilience Rating = 1% reduction to be crit and 2% less damage taken from critical strikes

**Comment by magey** [comment]
Tested on level 70 template characters. had 134 hit rating, 73 crit rating, 14 expertise rating. The other one had 186 defense rating, 48 dodge rating, 15 parry rating, 30 block rating.

Stat | Rating | Command | Result
-----|----|----|----
Hit|134|`/run print(134/GetCombatRatingBonus(CR_HIT_MELEE))`|15.769233419567
Crit|73|`/run print(73/GetCombatRatingBonus(CR_CRIT_MELEE))`|22.076923664843
Expertise|14|`/run print(14/GetCombatRatingBonus(CR_EXPERTISE))`|3.9423080112089
Defense|186|`/run print(186/GetCombatRatingBonus(CR_DEFENSE_SKILL))`|2.3653850351998
Dodge|48|`/run print(48/GetCombatRatingBonus(CR_DODGE))`|18.923078961979
Parry|15|`/run print(15/GetCombatRatingBonus(CR_PARRY))`|23.653846479203
Block|30|`/run print(30/GetCombatRatingBonus(CR_BLOCK))`|7.8846149990074
Resilience|179|`/run print(179/GetCombatRatingBonus(CR_RESILIENCE_CRIT_TAKEN))`|39.423081398499
