### ISSUE TITLE
World mob XP

### ISSUE THREAD

**Issue by ironskillet2** [magey/tbc-warrior#27]
The original TBC mob XP value was calculated from the following

level*5 + 235.

it is still using the azeroth formula of level*5 + 45

this problem does not appear to be happening in dungeons.

**Comment by ironskillet2** [comment]
this video, https://www.youtube.com/watch?v=2RIx7vDEGus

shows the paladin receiving the correct amount of XP using the formula of level*5 + 235. with ofcourse modifiers such as him having rested and the mobs being different levels. but as you can see its much higher than on BETA.

This is a VOD from the Beta, go to the part after blood furnace and put in the azeroth XP formula and you will find they match. 

https://www.twitch.tv/videos/960933012

**Comment by cannonpalms** [comment]
Another TBC source: https://youtu.be/OK3DAUvw1K4?t=127

* Character level: 63
* Mob level: 62
* Expected XP: `(63*5+235)*(1-1/17) = 517.6 ~= 518xp`
* XP received in source: `518xp`
* XP received in beta ([link](https://www.twitch.tv/videos/960448642?t=6h33m29s) character level here is different, but XP gain obviously differs): `367xp` 

Another source: https://youtu.be/UgPx5QsLifk?t=61

* XP received in source: `~140xp`
* XP received in beta ([link](https://www.twitch.tv/videos/960448642?t=6h0m58s)): `92xp`

**Comment by Aggrend** [comment]
We have a hotfix in flight for this and it should be out soon (tm).

**Comment by ironskillet2** [comment]
thanks blizzard! once i see the correct XP value showin up we can close this baby

**Comment by ironskillet2** [comment]
UPDATE, looking at the VOD from maitoz, 

https://www.twitch.tv/videos/960448041

at 2:19:13+ they start killing non-elite dogs. These are doing 1 of 2 things in regards to their XP.

They are using the azeroth formula, or suffering from a random -33% XP nerf simply for being non-elites in a dungeon.

To help confirm if this might only be affecting non-elite mobs, I need to see a clip of a world elite mob being killed.

**Comment by cannonpalms** [comment]
@Aggrend 

Can you confirm that this hotfix indeed went up as of the time of this blue post? We are not seeing any change to XP calculation at this time. 

https://eu.forums.blizzard.com/en/wow/t/testing-availability-and-fixes-25-march/263635

**Comment by viliustank** [comment]
![image](https://user-images.githubusercontent.com/51063082/112594278-11c0bf00-8ddf-11eb-8fb3-fa363f70d38b.png)
in that test just now i'm level 59 killing a level 59 mob in outland, 340 is the azeroth formula not outland formula

**Comment by magey** [comment]
This was just fixed on beta; tested it now:

![image](https://user-images.githubusercontent.com/44882404/112669589-f56d6280-8e70-11eb-8e51-ec9f37e834ac.png)

That's me at level 61 killing a level 62 vulture. The base XP formula is `(Char Level * 5) + 235 = 540`, then because it's a level 62 vulture there's a 1.05 multiplier which brings us to 567, times two for the rested XP.
