### ISSUE TITLE
Raid group swapping removes party-wide buffs

### ISSUE THREAD

**Issue by magey** [magey/tbc-warrior#30]
In the original Burning Crusade, swapping people between groups during a raid was a critical element of gameplay. It was used to facilitate popular tactics such as Bloodlust rotations (moving shamans to a selected group so they can cast Bloodlust and then moving them back to their original group) and Battle Shout buffing with the Solarian trinket to multiple groups. In the classic BC beta right now, moving someone to another group removes all their party-wide buffs and moving someone who cast his own buffs on a group removes all those buffs from party members.

Example: [Elitist Jerks - Zul'Aman(TBC) speed-Run](https://www.youtube.com/watch?v=eczxxR7hnkQ&t=232s)

In this video we can see Gurgthock move himself to another group, cast Bloodlust and then move himself back to his original group.

**Comment by magey** [comment]
Tested group swapping today on the beta (2.5.1 build 38225) as the level cap was raised to 70 and shamans have Bloodlust now:

https://user-images.githubusercontent.com/44882404/113907812-78ca7480-97de-11eb-866d-5adb112c9043.mp4

As can be seen in the video, Bloodlust group swapping works 🎉

Additionally I tested Battle Shout group swapping which still does not work.

**Comment by Aggrend** [comment]
Battle shout is intended to be removed when swapping groups. This matches all reference clients we have (from 2.0.1 to 2.4.3). This can be closed as NAB at this point as this is correct behavior.

**Comment by Jerrythemagicdog** [comment]
Seems to be consistent with other spells that use the same targeting as Battle Shout, Commanding Shout, etc.
One example is Unleashed Rage that can be seen in the same video: https://youtu.be/tOvwKfQiO5g?t=531
Gurgthock gains Unleashed Rage when he's in the same group as the Enhancement Shaman and loses it when he leaves the group.
