### ISSUE TITLE
Rampage AP stacking incorrectly

### ISSUE THREAD

**Issue by Frayed292** [magey/tbc-warrior#32]
My understanding is that Rampage (Rank 2) in the WoW TBC beta is supposed to add 40 attack power per stack, for a total of 200 AP. Currently Rampage is adding AP incorrectly. With a base AP of 1004, Rampage is increasing AP to 1044 AP at one stack, 1084 AP at two stacks, 1164 AP at 3 stacks, 1324 AP at 4 stacks, and 1644 AP at five stacks. 

https://user-images.githubusercontent.com/81474065/112722508-5d0ec680-8ee0-11eb-96a6-8624c994b31e.mp4

**Comment by magey** [comment]
Fixed today in 38225.
