### ISSUE TITLE
Racial expertise passives can be activated regardless of weapon type

### ISSUE THREAD

**Issue by ymmib** [magey/tbc-warrior#40]
Human and Orc racial expertise passives can be activated regardless of weapon type. For humans this is 10 expertise from mace and sword specialization, for orcs 5 expertise from axe specialization. When you equip a weapon you have a racial passive for you get 5 expertise a second time.
The bug is triggered on paladins by taking a point in Combat Expertise, on rogues by taking a point in Weapon Expertise, and on Warriors by taking a point in Defiance and swapping to defensive stance.
Paladin: https://streamable.com/ties6s
Rogue: https://streamable.com/np8kj9
Warrior: https://streamable.com/iga58a

edit: Defiance does trigger it. Thanks to Steelbreaker for telling me to swap stances!

**Comment by Aggrend** [comment]
This should be fixed in next week's (week of 4/5) beta build.
