### ISSUE TITLE
 /sit for Enrage and Blood Craze inconsistent - Patch 2.3 addition

### ISSUE THREAD

**Issue by mpuryear** [magey/tbc-warrior#41]
In patch 2.3 blizzard noted that /sit should now intentionally trigger these talents. /sit doesn't currently trigger them in a useful way on the beta.

https://wowwiki-archive.fandom.com/wiki/Patch_2.3.0

![image](https://user-images.githubusercontent.com/17075809/113281613-a5d8cd80-929a-11eb-8cd8-f7dc2684acd9.png)

![image](https://user-images.githubusercontent.com/17075809/113281586-9c4f6580-929a-11eb-9668-a80f76e38e41.png)

**Comment by magey** [comment]
This was reverted in [patch 2.3.2](https://gist.github.com/magey/6beb165ea93cdb010d5f22a21a9db5c2#file-patch-txt-L1549):

```
  * Effects triggered from being critically hit: Many abilities and
    talents were changed in 2.3.0 to allow them to trigger from critical
    strikes that occurred while the player benefitting from them was
    sitting. These abilities once again do not trigger if the victim is
    sitting.
```
