### ISSUE TITLE
Some proc events do not generate SPELL_AURA_REFRESH

### ISSUE THREAD

**Issue by magey** [magey/tbc-warrior#46]
We observed this behavior with Badge of the Swarmguard and Annihilator:
- Once the badge proc Insight of the Qiraji is stacked to 6 and it procs again, you can visually see it proc but you get no combat log event for the buff refresh
- For Annihilator the behavior is similar; if you proc the weapon with 3 stacks of the debuff already on the target, you can visually see it proc and the debuff duration is refreshed, but there is no event generated in the combat log

An abbreviated example from [this log of testing Annihilator](https://github.com/magey/tbc-warrior/files/6268147/WoWCombatLog-040721_013244.txt):

```
4/7 01:38:44.437  SPELL_AURA_APPLIED,"Armor Shatter",0x20,DEBUFF
4/7 01:39:25.116  SPELL_AURA_APPLIED_DOSE,"Armor Shatter",0x20,DEBUFF,2
4/7 01:40:06.984  SPELL_AURA_APPLIED_DOSE,"Armor Shatter",0x20,DEBUFF,3
4/7 01:42:37.162  SPELL_MISSED,"Armor Shatter",0x20,RESIST,nil,0
4/7 01:42:49.455  SPELL_AURA_REMOVED,"Armor Shatter",0x20,DEBUFF
```

Here we can see that the time elapsed between the `SPELL_AURA_APPLIED_DOSE` which stacked the debuff to 3 and the `SPELL_AURA_REMOVED` which removed it is `02:42.471` minutes which is only possible if the debuff was refreshed in-between (and indeed it was as confirmed by the player who recorded this log).

**Comment by Cleavis** [comment]
fixed in 2.5.1.38364
