### ISSUE TITLE
Still able to use Overpower after switching target

### ISSUE THREAD

**Issue by TheGroxEmpire** [magey/tbc-warrior#49]
This is different to how it worked in vanilla / classic where you lose Overpower "combo point" when you switch target. I cannot find anything on TBC patch notes referencing this change, further information would be helpful.

https://user-images.githubusercontent.com/47816228/114216018-87f12400-9990-11eb-9bd1-10e113bda148.mp4

**Comment by Scylla420** [comment]
They changed how combo points work with TBC. Switching targets is not enough to make a combo point fall off, you need to actually add a combo point to a different target to make your original target's combo points disappear.

[relevant patch note](https://gist.github.com/magey/6beb165ea93cdb010d5f22a21a9db5c2#file-patch-txt-L6722)

If you can find video from retail TBC that shows an inability to overpower in a situation like this then that's one thing, but this seems correct to me. If anyone has more information feel free to comment

**Comment by Cleavis** [comment]
tbc mechanics change to rogue combo points and overpower.  behavior described here is working as intended

**Comment by Cleavis** [comment]
just cross referencing reply on issue 51 for completion sake: https://github.com/magey/tbc-warrior/issues/51#issuecomment-817945718
