### ISSUE TITLE
Losing overpower charge on main target if secondary target(s) dodges whirlwind

### ISSUE THREAD

**Issue by TheGroxEmpire** [magey/tbc-warrior#51]
In extension of #49 testing, I tested the interaction of Overpower on cleave with Whirlwind. Grahandsixty scored a white dodge on the main target and casted Whirlwind thereafter which was dodged by another target. This result in Grahandsixty losing his overpower charge on the main target.
This does not look like something that's intended but I could not confirm.

https://user-images.githubusercontent.com/47816228/114228963-66e4ff00-99a1-11eb-9384-729cc79b6fc7.mp4

**Comment by Aggrend** [comment]
This is a bit janky, but this is correct behavior. Not a Bug.
