### ISSUE TITLE
Glancing damage reduction is inconsistent with TBC-era logs

### ISSUE THREAD

**Issue by magey** [magey/tbc-warrior#57]
Research done by vigo2 [over here](https://github.com/magey/tbc-warrior/issues/1#issuecomment-825579288) revealed that glancing blow damage reduction vs. boss mobs in an [extensive collection of WWS parses](http://sisuguild.fi/~juha/wws/) from that era does not match the known/accepted value of 35% that we currently measured on beta, but instead is around **25%**.

The glancing blow damage reduction formula for vanilla indeed calculated 35% reduction against boss mobs without any bonus weapon skill, but it's possible that when the glancing blow chance formula was changed in patch 2.1, the damage reduction formula changed as well.

Here's a direct link to his [spreadsheet aggregating the glance damage reduction from various fights](https://docs.google.com/spreadsheets/d/e/2PACX-1vSwB4EZdWkCjm2gVuufyTCtIc6T3e7VZ7p57Ex4GCkQuSHq766Kh-MeHItMvtpUdP4_3jWpNlhTxD7M/pubhtml).

**Comment by TheGroxEmpire** [comment]
I found a blue post where Tigole (04/02/2007) mentioned that they have reduced glancing blow damage penalty against target that is 1 - 3 level higher than the player.
> We’re also reducing the Glancing Blow damage penalty for creatures 1-3 levels higher than the player. This will have a significant effect on melee DPS as it relates to endgame melee dps. More details on this at a later time.
(http://blue.cardplace.com/newcache/us/88680668.htm)

**Comment by Aggrend** [comment]
This should be resolved in the next build pushed to beta (build 38502 or later). The glancing damage reduction should be a range between 15-35% (averaging 25%). It was previously and incorrectly 25-45%, which lines up with the tests done on beta so far.

**Comment by magey** [comment]
Fixed today in 2.5.1.38521
