### ISSUE TITLE
Client deletes all Logs/WoWCombatLog-*.txt files on startup

### ISSUE THREAD

**Issue by magey** [magey/tbc-warrior#58]
When starting up the game the clients deletes all the `WoWCombatLog-*.txt` files inside the `Logs` folder. This bug has caused many lost hours for unsuspecting players.

Current workaround is to always copy your log files to somewhere outside of the `Logs/` folder whenever the game crashes or you log out, before starting it up again.

**Comment by cannonpalms** [comment]
Workaround: Use `rsync` Windows analog to sync the `Logs/` folder elsewhere.

**Comment by magey** [comment]
Extremely happy to say this was fixed today in 2.5.1.38521
