### ISSUE TITLE
One-Handed Weapon Specialization doesn't affect Thunder Clap

### ISSUE THREAD

**Issue by vigo2** [magey/tbc-warrior#61]
The tooltip on One-Handed Weapon Specialization ("1H spec" for short) states it "Increases physical damage you deal when a one-handed melee weapon is equipped by n%", but it doesn't increase the damage dealt by Thunder Clap on the beta server.

Thunder Clap deals physical damage ("School Damage (Physical)"), and indeed Death Wish - which has the same "Apply Aura: Mod Damage Done % (Physical)" as 1H spec - increases Thunder Clap's damage as expected.

1H Spec additionally has "EquippedItemSubClassMask: 0x0000A091 (AXE, MACE, SWORD, FIST, DAGGER) set, which might limit the abilities it's affecting (e.g. to those "connected" with weapon or shield usage). However, the same EquippedItemSubClassMask is set for Paladin's 1H Spec, which was recently fixed to affect Consecration again: an ability similar to Thunder Clap in that it's wholly unconnected with weapon or shield usage.

**Comment by Aggrend** [comment]
This is consistent with the reference client. Not A Bug, unfortunately.
