### ISSUE TITLE
Focus intercept triggers auto attacks on focus target instead of main target

### ISSUE THREAD

**Issue by tribetv1** [magey/tbc-warrior#63]
Tested this multiple times and have a couple of recordings to share, as you can see in the following short clips my auto attack is hitting the incorrect (or unselected) target after a focus intercept.

This behaviour is not occurring with other focus abilities like pummel, seems exclusive to intercept based upon my testing.

Links below:

https://youtu.be/VCvPLXJN3VI

https://youtu.be/5cofHAz4rNw

**Comment by Aggrend** [comment]
Focus targets were't a thing in TBC (introduced in WotLK), but an engineer walked through this with me and the way that Intercept is specifically written (in original 2.4.3 code) is to initiate auto attack on its target. The fact that its your focus and not your primary is of no real consequence as far as Intercept is concerned.

Going to call this Not a Bug for now. Its a quirk of getting /focus a bit early, I suppose. Thanks for the report though!

**Comment by beriah** [comment]
The focus command was a thing in TBC, the focus frame was not in until 3.0.2 and could only be added via AddOns.
There are several mentions of /focus in the TBC patch notes, notably in 2.0.3:
```
User Interface
  * Macro Features
      o The following commands now support the [target=unit] macro
        option syntax: /startattack, /petattack, /target, /assist, /focus
```

and 2.1.0:
  ```
* User Interface Scripting
      o Macro Features:
          + You can use %f in chat text to refer to your focus, the same
            way %t or %n refers to your target.
```
You could also see a focus frame in nearly every PvP video of that time.

**Comment by Aggrend** [comment]
Ah yeah, you are totally right. Doesn't really change anything for this issue, however. Thanks!

**Comment by tribetv1** [comment]
Thanks for looking into this for me :)
