### ISSUE TITLE
Bloodthirst is not benefitting from Improved Hunter's Mark and Expose Weakness

### ISSUE THREAD

**Issue by magey** [magey/tbc-warrior#66]
When Improved Hunter's Mark and/or Expose Weakness are on the target, Bloodthirst does not benefit from the added melee AP. Normal melee swings and weapon-damage-based attacks like Whirlwind do benefit from the added AP. Some combat log screenshots follow:

#### BT Baseline + Improved Hunter's Mark:
![image](https://user-images.githubusercontent.com/44882404/118736238-c52bba00-b84a-11eb-9204-c958e81ab691.png)

#### BT Improved Hunter's Mark + Expose Weakness
![image](https://user-images.githubusercontent.com/44882404/118736252-cceb5e80-b84a-11eb-83f6-b4786519bb15.png)

#### WW Baseline + Improved Hunter's Mark 
![image](https://user-images.githubusercontent.com/44882404/118736609-aa0d7a00-b84b-11eb-9441-645670ee3375.png)

#### WW Improved Hunter's Mark + Expose Weakness
![image](https://user-images.githubusercontent.com/44882404/118736647-bbef1d00-b84b-11eb-82de-347825fef0dd.png)

As can be seen in these screenshots, the baseline damage for BT here is 468. It still hits for 468 after Imp. Hunter's Mark is applied, and still hits for 468 after Expose Weakness is applied. You can also see that normal melee swings and Whirlwind do get the benefit from the bonus AP of these debuffs.

**Comment by Lemonism** [comment]
[This video](https://www.youtube.com/watch?v=bQCjMtRe7YY) of a warrior fighting Illidan prior to patch 2.3.0 (verified by the presence of both Death Wish and Rampage) shows Bloodthirst not benefiting from Expose Weakness on the target.

At 5:57 in the video the warrior hits a Shadow Demon with BT for 811 damage WITH Expose Weakness applied
![image](https://user-images.githubusercontent.com/84942242/119906818-92518800-bf14-11eb-88b5-e3342a69ae4e.png)


Later at 10:23 in the video they hit another Shadow Demon with BT for 811 damage WITHOUT Expose Weakness applied and no separate AP buffs present
![image](https://user-images.githubusercontent.com/84942242/119906869-b1e8b080-bf14-11eb-8143-c579a0fe06aa.png)

**Comment by Aggrend** [comment]
This does in fact match 2.4.3. We had our wires crossed with Unleashed Rage and Improved Berserker stance, and have corrected those issues, but we've double (and triple) checked Improved Hunters Mark and Expose Weakness and they do not apply to Bloodthirst, specifically (but they do apply to white hits and other attacks). Thanks!
