### ISSUE TITLE
Equipping trinkets induces their internal cooldown

### ISSUE THREAD

**Issue by ghost** [magey/tbc-warrior#71]
Equipping a trinket that has an internal cooldown seems to induce its internal cooldown, preventing it from triggering during that time. For example: Dragonspine Trophy seems to be unable to activate its haste effect during the first 20 seconds after equipping. 

This was tested by:
1. Equipping the trinket from backpack
2. Attacking an enemy for 20 seconds
3. Recording the number of attacks made in that time

Not a single time out of 414 swings of my 2.6 speed weapon did Dragonspine Trophy's haste effect activate. Dragonspine Trophy has a 1ppm proc chance, which leads this scenario to have a 0.000001% of occuring.

This was a feature that was explicitly added to the game in [patch 3.2.0 during Wrath of the Lich King](https://web.archive.org/web/20100507230145/http://www.worldofwarcraft.com/patchnotes/patch3p2.html), and seems to be erroneously present in The Burning Crusade Classic:

> Items with Triggered Effects: These items generally have cooldowns on how often they can be triggered. Those cooldowns are now triggered each time the item is equipped (example: A trinket has a 45-second cooldown on an effect triggered by player attacks; when a player equips that item, the effect will be unable to be triggered for the first 45 seconds it is worn).

Unfortunately, equipping and unequipping a trinket isn't logged by the game, and so I cannot provide an exhaustive log of my testing. Here is a video sample of one of my tests: https://streamable.com/1w8hp7 / https://www.youtube.com/watch?v=IGf0lzutDn4. This methodology was repeated until I had an adequate sample size.

I also tested Quagmirran's Eye with the same methodology, and over 171 spell casts, the 10% chance to activate never occurred - a 0.0000015% chance.

**Comment by hasnogaems** [comment]
"which leads this scenario to have a 0.000001% of occuring."
Can you tell how u calculated that?

**Comment by ghost** [comment]
> Can you tell how u calculated that?

Chance to not proc over multiple swings = Chance to not proc ^ Number of swings * 100%
Chance to not proc = 1 - Proc chance
Proc chance = 1 proc per 60s of swings
60s of swings = 1 / (weapon speed) * 60s


(( 1 - (1 / ((1/2.6) * 60)) ) ^ 414) * 100 = 0.000001% chance to not proc over 414 swings of a 2.6 speed weapon

**Comment by kenneth-wow** [comment]
[Fixed in newest patch](https://streamable.com/c1i0aa) 

Scarab of the Infinite Cycle is 45 ICD, for reference.

**Comment by ghost** [comment]
[Can confirm](https://streamable.com/xzd64a) it is fixed as of 2.5.2.40011 on live servers with Dragonspine Trophy, the original test case.
